from __future__ import annotations

import pytest

from longmemeval.config import AgentConfig, ProviderConfig
from longmemeval.model_gateway import create_model_gateway
from longmemeval.models import (
    EmbeddingRequest,
    EmbeddingResponse,
    GenerationRequest,
    GenerationResponse,
    TokenUsage,
)


class FakeGenerationProvider:
    async def generate(self, request: GenerationRequest) -> GenerationResponse:
        provider = "gemini" if request.model.startswith("gemini") else "openai"
        return GenerationResponse(
            text=f"generated by {request.model}",
            model=request.model,
            provider=provider,
            usage=TokenUsage(input_tokens=5, output_tokens=2, total_tokens=7),
            latency_ms=3,
            request_id=f"request-{request.model}",
        )


class FakeEmbeddingProvider:
    async def embed(self, request: EmbeddingRequest) -> EmbeddingResponse:
        return EmbeddingResponse(
            embeddings=[[1.0, 0.0] for _ in request.inputs],
            model=request.model,
            provider="openai",
            usage=TokenUsage(input_tokens=4, total_tokens=4),
            latency_ms=2,
            request_id="embedding-request",
        )


@pytest.mark.asyncio
async def test_gateway_dispatches_named_roles_and_records_sanitized_calls(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(
        "longmemeval.model_gateway.create_provider", lambda config: FakeGenerationProvider()
    )
    monkeypatch.setattr(
        "longmemeval.model_gateway.create_embedding_provider",
        lambda config: FakeEmbeddingProvider(),
    )
    agent_config = AgentConfig.model_validate(
        {
            "entrypoint": "agents.current:create_agent",
            "models": {
                "memory_writer": {
                    "kind": "generation",
                    "provider": "gemini",
                    "model": "gemini-writer",
                    "temperature": 0.2,
                    "max_output_tokens": 200,
                },
                "memory_embedder": {
                    "kind": "embedding",
                    "provider": "openai",
                    "model": "text-embedding-test",
                    "dimensions": 2,
                },
            },
        }
    )
    gateway = create_model_gateway(
        ProviderConfig(provider="openai", model="gpt-answer"), agent_config.models
    )

    assert set(gateway.roles) == {"answer", "memory_writer", "memory_embedder"}
    assert "judge" not in gateway.roles

    gateway.begin_case()
    generated = await gateway.generate("memory_writer", "secret history")
    embedded = await gateway.embed("memory_embedder", ["memory one", "memory two"])
    calls = gateway.finish_case()

    assert generated.model == "gemini-writer"
    assert len(embedded.embeddings) == 2
    assert [call.role for call in calls] == ["memory_writer", "memory_embedder"]
    assert calls[0].parameters == {
        "temperature": 0.2,
        "reasoning_effort": None,
        "max_output_tokens": 200,
    }
    assert calls[1].item_count == 2
    serialized = "\n".join(call.model_dump_json() for call in calls)
    assert "secret history" not in serialized
    assert "memory one" not in serialized


@pytest.mark.asyncio
async def test_gateway_rejects_wrong_operation_for_role(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(
        "longmemeval.model_gateway.create_provider", lambda config: FakeGenerationProvider()
    )
    gateway = create_model_gateway(ProviderConfig(provider="openai", model="gpt-answer"), {})
    with pytest.raises(TypeError, match="generation role"):
        await gateway.embed("answer", ["text"])
    with pytest.raises(KeyError, match="unknown model role"):
        await gateway.generate("missing", "prompt")
